spring.datasource.url=${URL:jdbc:postgresql://localhost:5432/zaun}
spring.datasource.username=${USER_NAME:postgres}
spring.datasource.password=${PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true